### ISSUE TITLE
Django 1.11 AttributeError: type object 'ClearableFileInput' has no attribute 'template_with_initial'

### ISSUE THREAD

**Issue by pmalmgren** [un1t/django-file-resubmit#16]
Hello, thank you for maintaining this package! 😄 

I have been upgrading one of my projects to the 1.11 pre-release, and I've noticed that `file_resubmit/widgets.py` is having the following error:

```
  File "/Users/pmalmgren/code/project-dj1.11/project/forms.py", line 26, in <module>
    from file_resubmit.admin import AdminResubmitFileWidget
  File "/Users/pmalmgren/code/project-dj1.11/ve/lib/python2.7/site-packages/file_resubmit/admin.py", line 14, in <module>
    from .widgets import ResubmitBaseWidget, ResubmitFileWidget
  File "/Users/pmalmgren/code/project-dj1.11/ve/lib/python2.7/site-packages/file_resubmit/widgets.py", line 59, in <module>
    class ResubmitFileWidget(ResubmitBaseWidget):
  File "/Users/pmalmgren/code/project-dj1.11/ve/lib/python2.7/site-packages/file_resubmit/widgets.py", line 60, in ResubmitFileWidget
    template_with_initial = ClearableFileInput.template_with_initial
AttributeError: type object 'ClearableFileInput' has no attribute 'template_with_initial'
```

Taking a look at the [1.11 release widgets.py](https://github.com/django/django/blob/1.11b1/django/forms/widgets.py), it looks like `template_with_initial` and `template_with_clear` have been removed from the `ClearableFileInput` class.

**Comment by maddencs** [comment]
Hi, I'm going through trying to upgrade our app to Django 1.11 and came across the same bug. What I did was override the ClearableFileInput __init__ method to check the Django version before setting those attributes. I forked the branch, which you can clone from [my repo](https://github.com/maddencs/django-file-resubmit) if you'd like. I've created a [pull request](https://github.com/un1t/django-file-resubmit/pull/19/commits/273bb68b5835efb98dc78c5a930893e5cfdc7f5c) for my fix, too.

**Comment by maddencs** [comment]
I've now provided an alternate fix, because I couldn't decide which way was better. Here's the branch on my fork with the other method of fixing it where I used a try/except statement instead of calling `django.get_version()` and added some `@property` and setter methods for the removed fields. I figure this will might better compatibility.

**Comment by timonweb** [comment]
@maddencs I hope your fix will get merged in but it looks like project maintainer isn't here. Ilya please let us know if you're still supporting this project or should we fork it.

**Comment by un1t** [comment]
Hi, guys!
Sorry for not responding so long.
If you interested I may give you permission for this repo and pipy also.

**Comment by un1t** [comment]
@maddencs, would you like to maintain this project?

**Comment by timonweb** [comment]
@un1t let's wait for @maddencs, if he won't take it, I'd like to maintain this project.

**Comment by maddencs** [comment]
Good morning. I'll maintain the project. I'm not going anywhere. :) Plus, my coworker has some improvements he'd like to add, as well.

**Comment by un1t** [comment]
@maddencs, I sent invite. Please check your email.

**Comment by un1t** [comment]
@maddencs, what is your name on pypi?

**Comment by maddencs** [comment]
Thanks, Ilya. My pypi name is csmadden.

**Comment by un1t** [comment]
I added you to pypi.
Let me know if you need travis or something else.

**Comment by maddencs** [comment]
Thanks, Ilya. Still waking up, but I'll work on this later today.

**Comment by maddencs** [comment]
New version has been pushed to PyPI. Closing issue. Let me know if you have any further problems. I'll look at the other open issues later this weekend, unless someone else comes by and feels like resolving them...
